name: Advent of Code 2020
on: [push]

jobs:
        build:
                name: Run Ubuntu Python3.9
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Setup Python
                          uses: actions/setup-python@v2
                          with:
                                  python-version: 3.9
                                  architecture: x64
                        - name: Install Poetry
                          run: pip install poetry

                        - name: Install Module
                          run: poetry install

                        - name: Run Day 1
                          run: poetry run python advent_of_code/day_1/__init__.py

                        - name: Run Day 2
                          run: poetry run python advent_of_code/day_2/__init__.py

                        - name: Run Day 3
                          run: poetry run python advent_of_code/day_3/__init__.py
